image: Visual Studio 2017
test: off
artifacts:
- path: .\*.zip
before_deploy:
- ps: bash ./create_zip.sh
deploy:
- provider: GitHub
  tag: $LATEST_MS_TAG
  auth_token: $GITHUB_TOKEN
  artifact: .\*.zip
  on:
    $SHOULD_BUILD: yes