image: Visual Studio 2017
environment:
  matrix:
  - BUILDARCH: x64
  - BUILDARCH: ia32
install:
- ps: >-
   $env:Path -split ';'

    Install-Product node LTS x64

    choco install jq

    bash ./get_repo.sh

    $env:LATEST_MS_TAG="$(git -C vscode describe --tags)"

    git -C vscode revert 90c13ff d1fed9e --no-commit

    Write-Output "Reverted a couple commits preventing setup exe build.  There may be conflicts in build/tfs/:"

    git -C vscode status

    . .\check_tags.ps1
build_script:
- ps: >-
    .\build.ps1

    .\push_build_artifacts.ps1
test: off
deploy:
- provider: GitHub
  tag: $(LATEST_MS_TAG)
  auth_token: $(GITHUB_TOKEN)
  on:
    SHOULD_BUILD: yes
